project:
  type: website
  output-dir: docs

website:
  title: "Bella Kormos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About me
      - href: projects.qmd
        text: Projects
      - href: interests.qmd
        text: Interests
      - href: cv.qmd
        text: Resume
       

format:
  html:
    theme:
      light: morph
      dark: solar
    css: styles.css
    page-layout: full
    toc: true

editor: visual

